# Permalinks
permalink:           pretty

# Setup
title:               Erwin de Gier
tagline:             Speaking Geek
url:                 http://edegier.nl
paginate:            1
baseurl:             http://edegier.nl

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Erwin de Gier
  url:               http://edegier.nl
  email:             erwin@edegier.nl

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/erwindeg

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
