# Base configs
image_fulls_loc: "/images/fulls"

# UI configs
title: "Erwin de Gier photography"
subtitle: ""
author:  "Erwin de Gier"
header:
 title: "Photos"
 subtitle: "by Erwin de Gier"
footer:
 name: "Erwin de Gier photography"
 bio: "Motorsports, travel & street"
contact_email: erwin@edegier.nl
social_urls:
  instagram: "https://www.instagram.com/erwinshootsf1"
  twitter: "https://twitter.com/erwindeg"
